version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgres/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=p4ssw0rd
volumes:
  db-store:
